package enums

type AbortCode int64

const (
	ABORT_CODE_BELOW_MIN_REQUIRED_QUESTIONS_ANSWERED AbortCode = iota
	ABORT_CODE_NO_MATCHING_CANDIDATES
	ABORT_CODE_NO_OVERLAPPING_QUESTIONS
)

func (m AbortCode) String() string {
	switch m {
	case ABORT_CODE_BELOW_MIN_REQUIRED_QUESTIONS_ANSWERED:
		return "ABORT_CODE_BELOW_MIN_REQUIRED_QUESTIONS_ANSWERED"
	case ABORT_CODE_NO_MATCHING_CANDIDATES:
		return "ABORT_CODE_NO_MATCHING_CANDIDATES"
	case ABORT_CODE_NO_OVERLAPPING_QUESTIONS:
		return "ABORT_CODE_NO_OVERLAPPING_QUESTIONS"
	}
	return "UNKNOWN"
}
